# Generated by Django 5.1.6 on 2025-02-15 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storagefacilities',
            name='number',
        ),
        migrations.AddField(
            model_name='storagefacilities',
            name='capacity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='storagefacilities',
            name='square',
            field=models.IntegerField(null=True),
        ),
    ]
